import pandas as pd

def sql_str(v):
    if pd.isna(v):
        return "NULL"
    s = str(v).replace("'", "''")
    return f"'{s}'"

def sql_num(v):
    if pd.isna(v):
        return "NULL"
    return str(v)

def sql_date(v):
    if pd.isna(v):
        return "NULL"
    return f"'{v.date().isoformat()}'"

def sql_int(v):
    if pd.isna(v):
        return "NULL"
    return str(int(v))

BATCH = 250

def emit_inserts(out, table, columns, rows):
    for i in range(0, len(rows), BATCH):
        chunk = rows[i : i + BATCH]
        out.write(f"insert into public.{table} ({', '.join(columns)}) values\n")
        out.write(",\n".join(chunk))
        out.write("\non conflict (accord_code) do nothing;\n\n")

# ---- companies (Data_One_time.xlsx) ----
df1 = pd.read_excel("data/Data_One_time.xlsx", sheet_name="Sheet1", header=3)
df1 = df1.dropna(subset=["Accord Code"])
df1 = df1.drop_duplicates(subset=["Accord Code"], keep="first")

companies_cols = [
    "accord_code", "company_name", "ipo_list_date", "isin", "industry", "sector",
    "nse_symbol", "bse_code", "bse_52w_high_date", "bse_52w_high_price",
    "bse_ath_date", "bse_ath_price", "nse_52w_high_date", "nse_52w_high_price",
    "nse_ath_date", "nse_ath_price",
]

companies_rows = []
for _, r in df1.iterrows():
    vals = [
        sql_int(r["Accord Code"]),
        sql_str(r["Company Name"]),
        sql_date(r["IPO_List Date"]),
        sql_str(r["CD_ISIN No"]),
        sql_str(r["CD_Industry"]),
        sql_str(r["CD_Sector1"]),
        sql_str(r["CD_NSE Symbol"]),
        sql_str(None if pd.isna(r["CD_BSE Code"]) else int(r["CD_BSE Code"])),
        sql_date(r["SC_BSE 52 Wk High Date"]),
        sql_num(r["SC_BSE 52 Wk High Price"]),
        sql_date(r["SC_BSE All Time High Date"]),
        sql_num(r["SC_BSE All Time High Price"]),
        sql_date(r["SC_NSE 52 Wk High Date"]),
        sql_num(r["SC_NSE 52 Wk High Price"]),
        sql_date(r["SC_NSE All Time High Date"]),
        sql_num(r["SC_NSE All Time High Price"]),
    ]
    companies_rows.append("(" + ", ".join(vals) + ")")

# ---- sme_companies (Data_SME_list.xlsx) ----
df2 = pd.read_excel("data/Data_SME_list.xlsx", sheet_name="Sheet1", header=3)
df2 = df2.dropna(subset=["Accord Code"])
df2 = df2.drop_duplicates(subset=["Accord Code"], keep="first")

sme_cols = ["accord_code", "company_name", "isin", "industry"]

sme_rows = []
for _, r in df2.iterrows():
    vals = [
        sql_int(r["Accord Code"]),
        sql_str(r["Company Name"]),
        sql_str(r["CD_ISIN No"]),
        sql_str(r["CD_Industry"]),
    ]
    sme_rows.append("(" + ", ".join(vals) + ")")

with open("supabase/seed_data.sql", "w") as out:
    out.write("-- Generated by scripts/generate_seed.py from data/*.xlsx. Do not edit by hand.\n\n")
    emit_inserts(out, "companies", companies_cols, companies_rows)
    emit_inserts(out, "sme_companies", sme_cols, sme_rows)

print(f"companies rows: {len(companies_rows)}")
print(f"sme_companies rows: {len(sme_rows)}")
