import pandas as pd

def sql_str(v):
    if pd.isna(v):
        return "NULL"
    s = str(v).replace("'", "''")
    return f"'{s}'"

def sql_num(v):
    if pd.isna(v):
        return "NULL"
    return str(v)

def sql_date(v):
    if pd.isna(v):
        return "NULL"
    return f"'{v.date().isoformat()}'"

def sql_int(v):
    if pd.isna(v):
        return "NULL"
    return str(int(v))

BATCH = 250
MAX_FILE_BYTES = 1_800_000

columns = [
    "accord_code", "company_name", "ipo_list_date", "isin", "industry", "sector",
    "nse_symbol", "bse_code", "bse_52w_high_date", "bse_52w_high_price",
    "bse_ath_date", "bse_ath_price", "nse_52w_high_date", "nse_52w_high_price",
    "nse_ath_date", "nse_ath_price",
]

update_set = ",\n  ".join(f"{c} = excluded.{c}" for c in columns if c != "accord_code")

df = pd.read_excel("Data_One_time_v2.xlsx", sheet_name="Sheet1", header=3)
df = df.dropna(subset=["Accord Code"])
df = df.drop_duplicates(subset=["Accord Code"], keep="first")

rows = []
for _, r in df.iterrows():
    vals = [
        sql_int(r["Accord Code"]),
        sql_str(r["Company Name"]),
        sql_date(r["IPO_List Date"]),
        sql_str(r["CD_ISIN No"]),
        sql_str(r["CD_Industry"]),
        sql_str(r["CD_Sector1"]),
        sql_str(r["CD_NSE Symbol"]),
        sql_str(None if pd.isna(r["CD_BSE Code"]) else int(r["CD_BSE Code"])),
        sql_date(r["SC_BSE 52 Wk High Date"]),
        sql_num(r["SC_BSE 52 Wk High Price"]),
        sql_date(r["SC_BSE All Time High Date"]),
        sql_num(r["SC_BSE All Time High Price"]),
        sql_date(r["SC_NSE 52 Wk High Date"]),
        sql_num(r["SC_NSE 52 Wk High Price"]),
        sql_date(r["SC_NSE All Time High Date"]),
        sql_num(r["SC_NSE All Time High Price"]),
    ]
    rows.append("(" + ", ".join(vals) + ")")

statements = []
for i in range(0, len(rows), BATCH):
    chunk = rows[i : i + BATCH]
    statements.append(
        f"insert into public.companies ({', '.join(columns)}) values\n"
        + ",\n".join(chunk)
        + f"\non conflict (accord_code) do update set\n  {update_set};\n"
    )

header = "-- Generated by scripts/generate_companies_v2_upsert.py from Data_One_time_v2.xlsx\n\n"
part = 1
buf = [header]
buf_size = len(header)
files_written = 0

def flush():
    global part, buf, buf_size, files_written
    if len(buf) <= 1:
        return
    out_path = f"supabase/companies_v2_upsert_{part:02d}.sql"
    with open(out_path, "w") as f:
        f.write("".join(buf))
    files_written += 1
    part += 1
    buf = [header]
    buf_size = len(header)

for stmt in statements:
    if buf_size + len(stmt) > MAX_FILE_BYTES and len(buf) > 1:
        flush()
    buf.append(stmt)
    buf_size += len(stmt)
flush()

print(f"{len(df)} rows -> {files_written} file(s)")
